# Generated by Django 5.2.5 on 2025-08-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('Oficio_Salida', models.CharField(blank=True, max_length=100, null=True)),
                ('Víctimas_Relacionadas', models.CharField(blank=True, max_length=255, null=True)),
                ('Núm_Registro', models.CharField(blank=True, max_length=100, null=True)),
                ('Usuaria', models.CharField(blank=True, max_length=255, null=True)),
                ('Núm_Sol', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_Recepción_CIE', models.CharField(blank=True, max_length=50, null=True)),
                ('Acuse_CIE', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno CIE',
                'verbose_name_plural': 'Turnos CIE',
                'db_table': 'turno_cie',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
