# Generated by Django 5.2.5 on 2025-08-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronVictima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Año', models.IntegerField(blank=True, null=True)),
                ('NúmeroRegistro', models.IntegerField(blank=True, null=True)),
                ('AlfanúmericaRegistro', models.CharField(blank=True, max_length=100, null=True)),
                ('NombreVíctima', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaRegistro', models.CharField(blank=True, max_length=50, null=True)),
                ('TipoDelitoViolaciónDH', models.CharField(blank=True, db_column='TipoDelito.ViolaciónDH', max_length=255, null=True)),
                ('TipoVíctima', models.CharField(blank=True, max_length=100, null=True)),
                ('ExpedienteJudicial', models.CharField(blank=True, max_length=100, null=True)),
                ('ReconocimientoCalidadVíctima', models.CharField(blank=True, max_length=100, null=True)),
                ('PostMortem', models.CharField(blank=True, max_length=10, null=True)),
                ('AlcaldíaHechoVictimizante', models.CharField(blank=True, max_length=100, null=True)),
                ('NNA', models.CharField(blank=True, max_length=10, null=True)),
                ('Sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('Teléfono', models.CharField(blank=True, max_length=100, null=True)),
                ('CorreoElectrónico', models.CharField(blank=True, max_length=255, null=True)),
                ('GAP', models.CharField(blank=True, max_length=100, null=True)),
                ('CURP', models.CharField(blank=True, max_length=18, null=True)),
                ('TiempoModoLugar', models.TextField(blank=True, null=True)),
                ('Parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('CarpetaInvestigación', models.CharField(blank=True, max_length=100, null=True)),
                ('NombreRecomendacion', models.CharField(blank=True, max_length=255, null=True)),
                ('DerechosHumanosViolados', models.TextField(blank=True, null=True)),
                ('ClaveVíctimaRecomendación', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Víctima del Padrón',
                'verbose_name_plural': 'Víctimas del Padrón',
                'db_table': 'padron_victimas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
