# Generated by Django 5.2.5 on 2025-08-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Número_Solicitud', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_Solicitud', models.CharField(blank=True, max_length=50, null=True)),
                ('Fecha_Completo', models.CharField(blank=True, max_length=50, null=True)),
                ('Persona_Usuaria', models.CharField(blank=True, max_length=255, null=True)),
                ('Solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('Delito', models.CharField(blank=True, max_length=255, null=True)),
                ('Recomendación', models.CharField(blank=True, max_length=255, null=True)),
                ('Aceptación', models.CharField(blank=True, max_length=100, null=True)),
                ('FUDS', models.CharField(blank=True, max_length=100, null=True)),
                ('Reconocimiento_Víctima', models.CharField(blank=True, max_length=100, null=True)),
                ('Identificaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('Actas', models.CharField(blank=True, max_length=100, null=True)),
                ('CURP', models.CharField(blank=True, max_length=18, null=True)),
                ('Estatus_Solicitud', models.CharField(blank=True, max_length=100, null=True)),
                ('Tipo_Resolución', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_Resolución', models.CharField(blank=True, max_length=50, null=True)),
                ('Tiempo_Resolución', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Registro',
                'verbose_name_plural': 'Solicitudes de Registro',
                'db_table': 'solicitudes_registro',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
