# Generated by Django 5.2.5 on 2025-08-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha', models.CharField(blank=True, max_length=50, null=True)),
                ('Número_Oficio', models.CharField(blank=True, max_length=100, null=True)),
                ('Alfanúmerica_Oficio', models.CharField(blank=True, max_length=100, null=True)),
                ('Asunto', models.TextField(blank=True, null=True)),
                ('Destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('Tipo_Envío', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oficio de Salida',
                'verbose_name_plural': 'Oficios de Salida',
                'db_table': 'oficios_salida',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
