# Generated by Django 5.2.5 on 2025-08-22 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="hecho_victimizante",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hecho_Victimizante"
            ),
        ),
        migrations.AddField(
            model_name="expediente",
            name="notas",
            field=models.TextField(blank=True, null=True, verbose_name="Notas"),
        ),
        migrations.AddField(
            model_name="oficioentrada",
            name="anio",
            field=models.TextField(blank=True, null=True, verbose_name="Año"),
        ),
        migrations.AddField(
            model_name="oficioentrada",
            name="ruiz_escamilla",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ruiz_Escamilla"
            ),
        ),
        migrations.AddField(
            model_name="oficiosalida",
            name="anio",
            field=models.TextField(blank=True, null=True, verbose_name="Año"),
        ),
        migrations.AddField(
            model_name="solicitudregistro",
            name="anio",
            field=models.TextField(blank=True, null=True, verbose_name="Año"),
        ),
        migrations.AddField(
            model_name="solicitudregistro",
            name="solicitud",
            field=models.TextField(blank=True, null=True, verbose_name="Solicitud"),
        ),
        migrations.AddField(
            model_name="turnocie",
            name="anio",
            field=models.TextField(blank=True, null=True, verbose_name="Año"),
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona_notificada",
                    models.TextField(
                        blank=True, null=True, verbose_name="Persona_Notificada"
                    ),
                ),
                (
                    "nucleo_familiar",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nucleo_Familiar"
                    ),
                ),
                (
                    "relovi",
                    models.TextField(blank=True, null=True, verbose_name="RELOVI"),
                ),
                (
                    "delito_recomendacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Delito_Recomendacion"
                    ),
                ),
                (
                    "funcionario_notifico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Funcionario_Notifico"
                    ),
                ),
                (
                    "fecha",
                    models.TextField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "lugar_notificacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Lugar_Notificacion"
                    ),
                ),
                (
                    "soporte_documental",
                    models.TextField(
                        blank=True, null=True, verbose_name="Soporte_Documental"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
