# Generated by Django 5.2.5 on 2025-08-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "control_gestion",
            "0002_expediente_hecho_victimizante_expediente_notas_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oficioentrada",
            name="ruiz_escamilla",
        ),
        migrations.AddField(
            model_name="oficioentrada",
            name="numero_entrada",
            field=models.TextField(
                blank=True, null=True, verbose_name="Número_Entrada"
            ),
        ),
    ]
