# Generated by Django 5.2.5 on 2025-08-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_gestion", "0003_rename_ruiz_escamilla_to_numero_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficioentrada",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="oficios_entrada/",
                verbose_name="Archivo PDF",
            ),
        ),
    ]
