# Generated by Django 5.2.5 on 2025-08-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('número', models.CharField(blank=True, db_column='#', max_length=10, null=True)),
                ('Entrada', models.CharField(blank=True, max_length=100, null=True)),
                ('Recepción_CEAVI', models.CharField(blank=True, max_length=50, null=True)),
                ('Recepción_RELOVI', models.CharField(blank=True, max_length=50, null=True)),
                ('Autoridad_Dependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('Alfanúmerica_Entrada', models.CharField(blank=True, max_length=100, null=True)),
                ('Remitente', models.CharField(blank=True, max_length=255, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('Asunto', models.TextField(blank=True, null=True)),
                ('Solicitud_Registro', models.CharField(blank=True, max_length=100, null=True)),
                ('Término', models.CharField(blank=True, max_length=50, null=True)),
                ('NA', models.CharField(blank=True, max_length=50, null=True)),
                ('Atiende_Oficio', models.CharField(blank=True, max_length=255, null=True)),
                ('Notificación', models.CharField(blank=True, max_length=50, null=True)),
                ('Confirmó_Asignación', models.CharField(blank=True, max_length=50, null=True)),
                ('Formato', models.CharField(blank=True, max_length=100, null=True)),
                ('Evidencia_Respuesta', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oficio de Entrada',
                'verbose_name_plural': 'Oficios de Entrada',
                'db_table': 'oficios_entrada',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
