# Generated by Django 5.2.5 on 2025-08-19 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Victima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_registro",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Registro"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=200, verbose_name="Apellido Paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Apellido Materno",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("NB", "No Binario"),
                            ("NE", "No Especificado"),
                        ],
                        max_length=2,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "curp",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de CURP inválido",
                                regex="^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z][0-9]$",
                            )
                        ],
                        verbose_name="CURP",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "tipo_victimizacion",
                    models.CharField(
                        max_length=300, verbose_name="Tipo de Victimización"
                    ),
                ),
                ("fecha_hechos", models.DateField(verbose_name="Fecha de los Hechos")),
                (
                    "lugar_hechos",
                    models.CharField(
                        max_length=500, verbose_name="Lugar de los Hechos"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("PENDIENTE", "Pendiente"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Víctima",
                "verbose_name_plural": "Víctimas",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
