# Generated by Django 5.2.5 on 2025-08-19 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("padron_victimas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="victima",
            name="usuario_registro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="victimas_registradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que registró",
            ),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(
                fields=["numero_registro"], name="padron_vict_numero__b40d45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(fields=["curp"], name="padron_vict_curp_5873d1_idx"),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(
                fields=["fecha_hechos"], name="padron_vict_fecha_h_ad6815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(fields=["estado"], name="padron_vict_estado_b52292_idx"),
        ),
    ]
