# Generated by Django 5.2.5 on 2025-08-20 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="victima",
            name="curp",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de CURP inválido",
                        regex="^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z][0-9]$",
                    )
                ],
                verbose_name="CURP",
            ),
        ),
    ]
