# Generated by Django 5.2.5 on 2025-08-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0003_alter_victima_curp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="victima",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Nacimiento"
            ),
        ),
    ]
