# Generated by Django 5.2.5 on 2025-08-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0004_alter_victima_fecha_nacimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="victima",
            name="fecha_hechos",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de los Hechos"
            ),
        ),
    ]
