# Generated by Django 5.2.5 on 2025-08-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0005_alter_victima_fecha_hechos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="victima",
            name="numero_registro",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Registro"
            ),
        ),
    ]
