# Generated by Django 5.2.5 on 2025-08-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0006_alter_victima_numero_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="victima",
            name="alcaldia_hecho_victimizante",
            field=models.TextField(
                blank=True, null=True, verbose_name="AlcaldíaHechoVictimizante"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="alfanumerica_registro",
            field=models.TextField(
                blank=True, null=True, verbose_name="AlfanúmericaRegistro"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="anio",
            field=models.TextField(blank=True, null=True, verbose_name="Año"),
        ),
        migrations.AddField(
            model_name="victima",
            name="carpeta_investigacion",
            field=models.TextField(
                blank=True, null=True, verbose_name="CarpetaInvestigación"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="clave_victima_recomendacion",
            field=models.TextField(
                blank=True, null=True, verbose_name="ClaveVíctimaRecomendación"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="correo_electronico_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="CorreoElectrónico CSV"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="curp_csv",
            field=models.TextField(blank=True, null=True, verbose_name="CURP CSV"),
        ),
        migrations.AddField(
            model_name="victima",
            name="derechos_humanos_violados",
            field=models.TextField(
                blank=True, null=True, verbose_name="DerechosHumanosViolados"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="expediente_judicial",
            field=models.TextField(
                blank=True, null=True, verbose_name="ExpedienteJudicial"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="fecha_registro_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="FechaRegistro CSV"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="gap",
            field=models.TextField(blank=True, null=True, verbose_name="GAP"),
        ),
        migrations.AddField(
            model_name="victima",
            name="nna",
            field=models.TextField(blank=True, null=True, verbose_name="NNA"),
        ),
        migrations.AddField(
            model_name="victima",
            name="nombre_recomendacion",
            field=models.TextField(
                blank=True, null=True, verbose_name="NombreRecomendacion"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="nombre_victima_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="NombreVíctima CSV"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="numero_registro_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="NúmeroRegistro CSV"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="parentesco",
            field=models.TextField(blank=True, null=True, verbose_name="Parentesco"),
        ),
        migrations.AddField(
            model_name="victima",
            name="post_mortem",
            field=models.TextField(blank=True, null=True, verbose_name="PostMortem"),
        ),
        migrations.AddField(
            model_name="victima",
            name="reconocimiento_calidad_victima",
            field=models.TextField(
                blank=True, null=True, verbose_name="ReconocimientoCalidadVíctima"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="sexo_csv",
            field=models.TextField(blank=True, null=True, verbose_name="Sexo CSV"),
        ),
        migrations.AddField(
            model_name="victima",
            name="telefono_csv",
            field=models.TextField(blank=True, null=True, verbose_name="Teléfono CSV"),
        ),
        migrations.AddField(
            model_name="victima",
            name="tiempo_modo_lugar",
            field=models.TextField(
                blank=True, null=True, verbose_name="TiempoModoLugar"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="tipo_delito_violacion_dh",
            field=models.TextField(
                blank=True, null=True, verbose_name="TipoDelito.ViolaciónDH"
            ),
        ),
        migrations.AddField(
            model_name="victima",
            name="tipo_victima",
            field=models.TextField(blank=True, null=True, verbose_name="TipoVíctima"),
        ),
    ]
