# Generated by Django 5.2.5 on 2025-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0007_victima_alcaldia_hecho_victimizante_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="victima",
            name="sexo_csv",
        ),
        migrations.AlterField(
            model_name="victima",
            name="alcaldia_hecho_victimizante",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "NA"),
                    ("Tlalpan", "Tlalpan"),
                    ("Cuauhtémoc", "Cuauhtémoc"),
                    ("Iztapalapa", "Iztapalapa"),
                    ("Gustavo A. Madero", "Gustavo A. Madero"),
                    ("Miguel Hidalgo", "Miguel Hidalgo"),
                    ("Álvaro Obregón", "Álvaro Obregón"),
                    ("Benito Juárez", "Benito Juárez"),
                    ("Coyoacán", "Coyoacán"),
                    ("Azcapotzalco", "Azcapotzalco"),
                    ("Venustiano Carranza", "Venustiano Carranza"),
                    ("Xochimilco", "Xochimilco"),
                    ("La Magdalena Contreras", "La Magdalena Contreras"),
                    ("Milpa Alta", "Milpa Alta"),
                    ("Tláhuac", "Tláhuac"),
                    ("Cuajimalpa de Morelos", "Cuajimalpa de Morelos"),
                    ("Iztacalco", "Iztacalco"),
                    ("Atizapán de Zaragoza", "Atizapán de Zaragoza"),
                    ("Foráneo", "Foráneo"),
                    ("Estado de México", "Estado de México"),
                    ("No especificado", "No especificado"),
                ],
                max_length=50,
                null=True,
                verbose_name="AlcaldíaHechoVictimizante",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="anio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                    ("2023", "2023"),
                    ("2024", "2024"),
                    ("2025", "2025"),
                    ("2026", "2026"),
                    ("2027", "2027"),
                    ("2028", "2028"),
                    ("2029", "2029"),
                    ("2030", "2030"),
                ],
                max_length=4,
                null=True,
                verbose_name="Año",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="gap",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "NA"),
                    ("Migrante", "Migrante"),
                    ("Indígena", "Indígena"),
                    ("NNA", "NNA"),
                    ("Discapacidad", "Discapacidad"),
                    ("PAM", "PAM"),
                    ("Refugiado", "Refugiado"),
                    ("Defensor DH", "Defensor DH"),
                    ("Periodista", "Periodista"),
                ],
                max_length=20,
                null=True,
                verbose_name="GAP",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="nna",
            field=models.CharField(
                blank=True,
                choices=[("0", "No"), ("1", "Sí"), ("NA", "NA")],
                max_length=2,
                null=True,
                verbose_name="NNA",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="parentesco",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "NA"),
                    ("Madre", "Madre"),
                    ("Padre", "Padre"),
                    ("Hermana", "Hermana"),
                    ("Hijo", "Hijo"),
                    ("Hija", "Hija"),
                    ("Cuñada", "Cuñada"),
                    ("Esposa", "Esposa"),
                    ("Hermano", "Hermano"),
                    ("Hijastro", "Hijastro"),
                    ("Concubina", "Concubina"),
                    ("Tía", "Tía"),
                    ("Sobrina", "Sobrina"),
                    ("Abuelo", "Abuelo"),
                    ("Abuela", "Abuela"),
                ],
                max_length=20,
                null=True,
                verbose_name="Parentesco",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="post_mortem",
            field=models.CharField(
                blank=True,
                choices=[("NA", "NA"), ("0", "No"), ("1", "Sí")],
                max_length=2,
                null=True,
                verbose_name="PostMortem",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="reconocimiento_calidad_victima",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Delito - MP", "Delito - MP"),
                    ("Delito – MP", "Delito – MP"),
                    ("Violación DH", "Violación DH"),
                    ("NA", "NA"),
                    ("Delito - Judicial", "Delito - Judicial"),
                    ("Delito – Judicial", "Delito – Judicial"),
                ],
                max_length=30,
                null=True,
                verbose_name="ReconocimientoCalidadVíctima",
            ),
        ),
        migrations.AlterField(
            model_name="victima",
            name="tipo_victima",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Directa", "Directa"),
                    ("Indirecta", "Indirecta"),
                    ("Potencial", "Potencial"),
                ],
                max_length=20,
                null=True,
                verbose_name="TipoVíctima",
            ),
        ),
    ]
