# Generated by Django 5.2.5 on 2025-08-20 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0008_remove_victima_sexo_csv_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(
                fields=["alfanumerica_registro"], name="padron_vict_alfanum_1e0302_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(
                fields=["numero_registro_csv"], name="padron_vict_numero__b10363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(fields=["anio"], name="padron_vict_anio_892e0a_idx"),
        ),
        migrations.AddIndex(
            model_name="victima",
            index=models.Index(
                fields=["tipo_victima"], name="padron_vict_tipo_vi_92c62a_idx"
            ),
        ),
    ]
