# Generated by Django 5.2.5 on 2025-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padron_victimas", "0009_victima_padron_vict_alfanum_1e0302_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="victima",
            name="numero_orden",
            field=models.IntegerField(
                blank=True,
                help_text="Número extraído para ordenamiento",
                null=True,
                verbose_name="Número de Orden",
            ),
        ),
    ]
